### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by JohnVict0r** [sedir/agenda_de_contatos#1]
Problema: 

$ python3 main.py     
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import PySimpleGUI as sg
  File "/home/john/Documents/workspace/git/agenda_de_contatos/venv/lib/python3.6/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/home/john/Documents/workspace/git/agenda_de_contatos/venv/lib/python3.6/site-packages/PySimpleGUI/PySimpleGUI.py", line 103, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'`

Solução:
`sudo apt-get install python3-tk`

**Comment by g4b-dev** [comment]
melhor forma - pip install PySimpleGUI
